import { DM_Sans, Barlow } from "next/font/google";
import "./globals.css";

const dmSans = DM_Sans({
  variable: "--font-dmSans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const barlow = Barlow({
  variable: "--font-barlow",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // Usar .className asegura que los estilos @font-face se carguen globalmente.
    // Aplicar las clases al <html> garantiza que las fuentes estén disponibles en toda la aplicación.
    <html lang="en" className={`${dmSans.className} ${barlow.className} antialiased`}>
      <body
        className="antialiased"
      >
        {children}
      </body>
    </html>
  );
}
